### ISSUE TITLE
Error Downloading Contacts from Internet

### ISSUE THREAD

**Issue by JGPorteous** [rogerclarkmelbourne/radioddity_gd-77_cps#62]
I found a bug on the version I had installed of CPS Community Edition.

On the "Download Contacts" form, when Clicking "Download from DMR MARC" I got the below error:
System.Net.WebException: The request was aborted: Could not create SSL/TLS secure channel.
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   at System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)

I downloaded the source and found that the behavior changed to display an error from the language dictionary item: UnableDownloadFromInternet, which says "Unable to download data. Please check your Internet connection"

Recommendations & Notes:
1. Update error to show a more meaningful error, to help troubleshooting, or implement logging with more details.
2. Update the URLs to HTTPS, as this resolved the bug I had but only for the "Download from URL".
3. Still to determine how to get values of exception during debugging to fix error when clicking "Download from DMR MARC"

**Comment by rogerclarkmelbourne** [comment]
I don't think its worth retaining this feature.

I put it in when the ham-digital download wasnt working while ham-digital was offline.

Now that ham-digital has been working reliably for at least 6 months, I think I will just remove the DMR MARC option

**Comment by rogerclarkmelbourne** [comment]
I think I'll remove this as I added an option to import the users.csv which can be downloaded from Radioid.net into the DMR ID system
